project:
  type: book

book:
  title: "Personal Notes: A Student's Guide to Bayesian Statistics"
  author: "Peter Baumgartner"
  date: last-modified
  date-format: YYYY-MM-DD HH:mm
  favicon: "img/apple-touch-icon.png"
  search: true
  repo-url: https://github.com/petzi53/bayesian-statistics/
  repo-actions: [edit]
  sharing: [twitter, facebook]

  chapters:
    - index.qmd
    - 01-intro.qmd
    - part: part-one.qmd
      chapters:
        - 02-subjective-worlds.qmd
        - 03-probability.qmd
        - 80-references.qmd
  appendices:
    - 90-example-1.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: glossary.css
    number-sections: true
    toc: true
    toc-depth: 4
    toc-expand: 2
    code-fold: false
    code-tools: true
    code-link: true
    code-overflow: scroll
    df-print: default

knitr:
  opts_chunk:
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true


execute:
    freeze: auto


# https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language.yml
language:
   crossref-fig-title: "Image"
   crossref-tbl-title: "Tabulation"
   crossref-prp-title: "Callout"
   crossref-lem-title: "Video"
   section-title-appendices: "APPENDICES"

   callout-note-title: "Note"            # blue
   callout-tip-title: "Tip"         # green
   callout-warning-title: "Wach out!"    # orange
   callout-important-title: "Important"  # red
   callout-caution-title: "TODO"         # yellow

comments:
  hypothesis: true
